EmailClient.WEB/Models/EmailClient.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EmailClients.WEB.Models
{
    public class EmailClient
    {
      public int Id { get; set; }
      public string Name { get; set; }
      public string Surname { get; set; }
      public string Nickname { get; set; }
      public int Age { get; set; }
      public string Email { get; set; }
     
    }
}

EmailClient.WEB/Controllers/EmailClientController.cs
using System.Collections.Generic;
using System.Net;
using System.Text;
using Newtonsoft.Json;
using System.Web.Mvc;
using EmailClients.WEB.Models;
using System.Data.SqlClient;
using System.Data;
using System;
using System.Net.Mail;

namespace EmailClients.WEB.Controllers
{
    public class EmailClientController : Controller
    {
        static string connectionString = "Server = sqltest; Database = EmailClientDB; User ID = -----; Password = ---------;";
        SqlConnection conn = new SqlConnection(connectionString);
        static WebClient webclient = new WebClient();


        static EmailClient DeserializeJson(string serializedObj)
        {
            EmailClient deserializedEmailClient = JsonConvert.DeserializeObject<EmailClient>(serializedObj);
            return deserializedEmailClient;
        }

        static List<EmailClient> DeserializeJsonList(byte[] serializedObj)
        {
            List<EmailClient> deserializedEmailClients = JsonConvert.DeserializeObject<List<EmailClient>>(Encoding.GetEncoding("Windows-1254").GetString(serializedObj), new JsonSerializerSettings { TypeNameHandling = TypeNameHandling.All });
            return deserializedEmailClients;
        }

        static EmailClient GetObject(string path) // to get an EmailClient object from API with ID by URL
        {
            var response = webclient.DownloadString("http://localhost:6666/api/emailclient/GetByID/1");
            return DeserializeJson(response);
        }

        static List<EmailClient> GetAllObjects(string path) // to get a list of EmailClient objects from API
        {
            var response = webclient.DownloadData(path);
            return DeserializeJsonList(response);
        }

        public List<EmailClient> GetClientListfromDB() // to get a list of EmailClient objects from DB
        {
            List<EmailClient> emails = new List<EmailClient>();
            string commandText2 = "SELECT Name,Surname,Nickname,Email,Age FROM clients";
            conn.Open();
            SqlCommand cmd = new SqlCommand(commandText2, conn);
            SqlDataReader sqlreader = cmd.ExecuteReader();
            DataTable dt = new DataTable();
            dt.Load(sqlreader);

            foreach (DataRow row in dt.Rows)
            {
                var newEmail = new EmailClient();
                newEmail.Name = (string)row["Name"];
                newEmail.Surname = (string)row["Surname"];
                newEmail.Nickname = (string)row["Nickname"].ToString();
                newEmail.Email = (string)row["Email"].ToString();
                newEmail.Age = (int)row["Age"];
                emails.Add(newEmail);
            }
            conn.Close();
            return emails;
        }

        public void InsertNewUser(EmailClient emailClient) // to insert a new EmailClient object to DB
        {
            if (emailClient.Name.Length <= 30 && emailClient.Surname.Length <= 30 && emailClient.Nickname.Length <= 30 && emailClient.Email.Length <= 40 && emailClient.Age.GetType() == typeof(Int32))
            {
                string commandText =
                    "BEGIN IF NOT EXISTS(SELECT * FROM clients WHERE Nickname = '" + emailClient.Nickname + "') BEGIN " +
                    " INSERT INTO clients(Name,Surname,Nickname,Email,Age) " +
                    "VALUES('" + emailClient.Name + "','" + emailClient.Surname +
                    "','" + emailClient.Nickname + "','" + emailClient.Email + "'," + emailClient.Age + ") END END";

                SqlCommand command = new SqlCommand(commandText, conn);
                command.Connection.Open();
                command.ExecuteNonQuery();
                command.Connection.Close();
            }
        }

        public ActionResult GetClientListfromController()
        {

            return View();
        }

        public ActionResult Index()
        {
            var emailClients = GetClientListfromDB();
            return View(emailClients);
        }

        [HttpPost]
        public ActionResult SendMethod(string name, string surName, string nickName, string eMail, string age)
        {
            string commandText = "SELECT Name,Surname,Nickname,Email,Age FROM clients WHERE Nickname = @nickname";
            SqlCommand command = new SqlCommand(commandText, conn);
            SmtpClient smtpServer = new SmtpClient("write some number here", 666)
            {
                Credentials = new System.Net.NetworkCredential("", ""),
                EnableSsl = false
            };
            EmailClient newEmailClient = new EmailClient
            {
                Name = name,
                Surname = surName,
                Nickname = nickName,
                Email = eMail,
                Age = Int32.Parse(age)
            };

            InsertNewUser(newEmailClient);

            if (ModelState.IsValid)
            {
                command.Parameters.Add("@nickname", SqlDbType.NVarChar, nickName.Length).Value = nickName;
                command.Connection.Open();
                SqlDataReader sqlDataReader = command.ExecuteReader();

                // e-Mail sending section
                while (sqlDataReader.Read())
                {
                    MailMessage mailMessage = new MailMessage("gorkem.temiz@yemeksepeti.com",
                                                               sqlDataReader["Email"].ToString())
                            {
                             Subject = "uygulama test maili",
                                Body = sqlDataReader["Name"] + "\t"
                                     + sqlDataReader["Surname"] + "\t"
                                     + sqlDataReader["Age"].ToString() + "\t"
                                     + sqlDataReader["Nickname"] + "\t"
                            };
                    smtpServer.Send(mailMessage);
                }
            }
            return RedirectToAction("Index");
        }
    }
}

EmailClient.WEB/Views/EmailClient/Index.cshtml
@using EmailClients.WEB.Models;
@model List<EmailClients.WEB.Models.EmailClient>

<!DOCTYPE html>
<html>
<head>
<style>
    div.yarila{max-width:50%}
</style>
    @{ var clientList = ViewData["emailClients"] as List<EmailClient>;
        <title> @ViewBag.Title = "ClientListe"; </title>
    }
</head>
<body>
    <div>
        <div class="yarila" id="list" align="left">
         <h2> List of Registered Clients</h2>
            <ul>
                @foreach (var client in Model)
                 {
                <li>
                    <b>Ad:</b> @client.Name
                    <br />
                    <b>Soyad:</b> @client.Surname
                    <br />
                    <b>Nick:</b> @client.Nickname
                    <br />
                    <b>Yaş:</b> @client.Age.ToString()
                    <br> <br />
                </li>
                 }
            </ul>
        </div>
        @* dfsdfsdkljfsldknfljkasdmnfşosdfğoısdmf ıomfdıof
            dsfadsfsadf
            sdfsdfasdfsdgfdgr
            e
            g
            eg
            fdg
            
            fdg
            fdg
            *@
        <div class="yarila" id="register" align="right" style="float:right">
            <h2> Registration of a New Client </h2>
            @using (Html.BeginForm("SendMethod", "EmailClient", FormMethod.Post))
             {
                <b>Ad:</b> @Html.TextBox("name")
                <br />
                <b>Soyad:</b> @Html.TextBox("surName")
                <br />
                <b>Nick:</b> @Html.TextBox("nickName")
                <br />
                <b>Yaş:</b> @Html.TextBox("age")
                <br>
                <b>e-Mail:</b> @Html.TextBox("eMail")
                <br />
                <input type="submit" name="submitButton" value="Send" />
             }
        </div>
    </div>
</body>
</html>

EmailClient.WEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - GoMail Client Page</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("GoMail Client Page", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - GoMail</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>